name: 'dvdrental'
version: '1.0.0'
config-version: 2

profile: 'dvdrental'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
metric-paths: ["metrics"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  dvdrental:
    materialized: view
    staging:
      materialized: view
    dims:
      materialized: table
    facts:
      materialized: table

metrics:
  dvdrental:
    path: metrics
    enabled: true 